python3 main.py benchmark/mzzv11.mps.gz
python3 main.py benchmark/neos-5093327-huahum.mps.gz
python3 main.py benchmark/sing44.mps.gz
python3 main.py benchmark/neos-5075914-elvire.mps.gz
python3 main.py benchmark/supportcase19.mps.gz
python3 main.py benchmark/splice1k1.mps.gz
python3 main.py benchmark/neos-4722843-widden.mps.gz
python3 main.py benchmark/neos-5052403-cygnet.mps.gz
python3 main.py benchmark/supportcase12.mps.gz
python3 main.py benchmark/qap10.mps.gz
python3 main.py benchmark/proteindesign122trx11p8.mps.gz
python3 main.py benchmark/rd-rplusc-21.mps.gz
python3 main.py benchmark/snp-02-004-104.mps.gz
python3 main.py benchmark/neos-3988577-wolgan.mps.gz
python3 main.py benchmark/n2seq36q.mps.gz
python3 main.py benchmark/neos17.mps.gz
python3 main.py benchmark/fiball.mps.gz
python3 main.py benchmark/lectsched-5-obj.mps.gz
python3 main.py benchmark/nw04.mps.gz
python3 main.py benchmark/piperout-08.mps.gz
python3 main.py benchmark/ex9.mps.gz
python3 main.py benchmark/drayage-25-23.mps.gz
python3 main.py benchmark/uccase9.mps.gz
python3 main.py benchmark/n9-3.mps.gz
python3 main.py benchmark/nursesched-medium-hint03.mps.gz
python3 main.py benchmark/neos-3754224-navua.mps.gz
python3 main.py benchmark/satellites2-40.mps.gz
python3 main.py benchmark/seymour1.mps.gz
python3 main.py benchmark/nursesched-sprint02.mps.gz
python3 main.py benchmark/irp.mps.gz
python3 main.py benchmark/neos-4532248-waihi.mps.gz
python3 main.py benchmark/cost266-UUE.mps.gz
python3 main.py benchmark/ns1760995.mps.gz
python3 main.py benchmark/eilA101-2.mps.gz
python3 main.py benchmark/neos-4338804-snowy.mps.gz
python3 main.py benchmark/mc11.mps.gz
python3 main.py benchmark/neos859080.mps.gz
python3 main.py benchmark/trento1.mps.gz
python3 main.py benchmark/sp97ar.mps.gz
python3 main.py benchmark/supportcase40.mps.gz
python3 main.py benchmark/neos-933966.mps.gz
python3 main.py benchmark/neos-3046615-murg.mps.gz
python3 main.py benchmark/exp-1-500-5-5.mps.gz
python3 main.py benchmark/academictimetablesmall.mps.gz
python3 main.py benchmark/ns1116954.mps.gz
python3 main.py benchmark/assign1-5-8.mps.gz
python3 main.py benchmark/fhnw-binpack4-4.mps.gz
python3 main.py benchmark/physiciansched6-2.mps.gz
python3 main.py benchmark/momentum1.mps.gz
python3 main.py benchmark/irish-electricity.mps.gz
python3 main.py benchmark/neos-4300652-rahue.mps.gz
python3 main.py benchmark/neos-1582420.mps.gz
python3 main.py benchmark/rail01.mps.gz
python3 main.py benchmark/fast0507.mps.gz
python3 main.py benchmark/square47.mps.gz
python3 main.py benchmark/buildingenergy.mps.gz
python3 main.py benchmark/swath3.mps.gz
python3 main.py benchmark/gen-ip002.mps.gz
python3 main.py benchmark/cbs-cta.mps.gz
python3 main.py benchmark/nexp-150-20-8-5.mps.gz
python3 main.py benchmark/pg.mps.gz
python3 main.py benchmark/beasleyC3.mps.gz
python3 main.py benchmark/lotsize.mps.gz
python3 main.py benchmark/icir97_tension.mps.gz
python3 main.py benchmark/chromaticindex512-7.mps.gz
python3 main.py benchmark/neos-3656078-kumeu.mps.gz
python3 main.py benchmark/glass-sc.mps.gz
python3 main.py benchmark/n3div36.mps.gz
python3 main.py benchmark/drayage-100-23.mps.gz
python3 main.py benchmark/supportcase18.mps.gz
python3 main.py benchmark/30n20b8.mps.gz
python3 main.py benchmark/neos5.mps.gz
python3 main.py benchmark/istanbul-no-cutoff.mps.gz
python3 main.py benchmark/nu25-pr12.mps.gz
python3 main.py benchmark/cod105.mps.gz
python3 main.py benchmark/neos-4763324-toguru.mps.gz
python3 main.py benchmark/mcsched.mps.gz
python3 main.py benchmark/uccase12.mps.gz
python3 main.py benchmark/chromaticindex1024-7.mps.gz
python3 main.py benchmark/sing326.mps.gz
python3 main.py benchmark/net12.mps.gz
python3 main.py benchmark/neos-3004026-krka.mps.gz
python3 main.py benchmark/s250r10.mps.gz
python3 main.py benchmark/rmatr100-p10.mps.gz
python3 main.py benchmark/radiationm18-12-05.mps.gz
python3 main.py benchmark/neos-957323.mps.gz
python3 main.py benchmark/neos-3083819-nubu.mps.gz
python3 main.py benchmark/seymour.mps.gz
python3 main.py benchmark/milo-v12-6-r2-40-1.mps.gz
python3 main.py benchmark/b1c1s1.mps.gz
python3 main.py benchmark/neos-5188808-nattai.mps.gz
python3 main.py benchmark/csched008.mps.gz
python3 main.py benchmark/neos-1171448.mps.gz
python3 main.py benchmark/neos-4738912-atrato.mps.gz
python3 main.py benchmark/neos-950242.mps.gz
python3 main.py benchmark/ex10.mps.gz
python3 main.py benchmark/neos-3555904-turama.mps.gz
python3 main.py benchmark/graphdraw-domain.mps.gz
python3 main.py benchmark/supportcase6.mps.gz
python3 main.py benchmark/mzzv42z.mps.gz
