python3 main.py cbc-test-set-master/10teams.mps.gz
python3 main.py cbc-test-set-master/116_205_1262_66.mps.gz
python3 main.py cbc-test-set-master/121_147_1345_33.mps.gz
python3 main.py cbc-test-set-master/121_147_1345_33_pp.mps.gz
python3 main.py cbc-test-set-master/22433.mps.gz
python3 main.py cbc-test-set-master/23588.mps.gz
python3 main.py cbc-test-set-master/2club200v15p5scn.mps.gz
python3 main.py cbc-test-set-master/30_70_45_05_100.mps.gz
python3 main.py cbc-test-set-master/30n20b8.mps.gz
python3 main.py cbc-test-set-master/50v-10.mps.gz
python3 main.py cbc-test-set-master/a05100.mps.gz
python3 main.py cbc-test-set-master/a10100.mps.gz
python3 main.py cbc-test-set-master/A-1.mps.gz
python3 main.py cbc-test-set-master/a2864-99blp.mps.gz
python3 main.py cbc-test-set-master/a2c1s1.mps.gz
python3 main.py cbc-test-set-master/A-2.mps.gz
python3 main.py cbc-test-set-master/A-4-cuts.mps.gz
python3 main.py cbc-test-set-master/A-5.mps.gz
python3 main.py cbc-test-set-master/academictimetablebig.mps.gz
python3 main.py cbc-test-set-master/academictimetablesmall.mps.gz
python3 main.py cbc-test-set-master/acc-tight2.mps.gz
python3 main.py cbc-test-set-master/acc-tight4.mps.gz
python3 main.py cbc-test-set-master/acc-tight5.mps.gz
python3 main.py cbc-test-set-master/adult-max5features.mps.gz
python3 main.py cbc-test-set-master/air03.mps.gz
python3 main.py cbc-test-set-master/air04.mps.gz
python3 main.py cbc-test-set-master/air05.mps.gz
python3 main.py cbc-test-set-master/aligninq.mps.gz
python3 main.py cbc-test-set-master/allcolor10.mps.gz
python3 main.py cbc-test-set-master/allcolor58.mps.gz
python3 main.py cbc-test-set-master/app1-1.mps.gz
python3 main.py cbc-test-set-master/app3.mps.gz
python3 main.py cbc-test-set-master/ash608gpia-3col.mps.gz
python3 main.py cbc-test-set-master/assign1-10-4.mps.gz
python3 main.py cbc-test-set-master/assign1-5-8.mps.gz
python3 main.py cbc-test-set-master/atlanta-ip.mps.gz
python3 main.py cbc-test-set-master/atm20-100.mps.gz
python3 main.py cbc-test-set-master/attfInst1.mps.gz
python3 main.py cbc-test-set-master/attfInst2.mps.gz
python3 main.py cbc-test-set-master/attfInst3.mps.gz
python3 main.py cbc-test-set-master/attfInst4.mps.gz
python3 main.py cbc-test-set-master/attfInstA.mps.gz
python3 main.py cbc-test-set-master/attfInstC.mps.gz
python3 main.py cbc-test-set-master/attfInstD.mps.gz
python3 main.py cbc-test-set-master/australia_ABS_L1-CTA.mps.gz
python3 main.py cbc-test-set-master/b2c1s1.mps.gz
python3 main.py cbc-test-set-master/bab1.mps.gz
python3 main.py cbc-test-set-master/bab2.mps.gz
python3 main.py cbc-test-set-master/bab3.mps.gz
python3 main.py cbc-test-set-master/bab5.mps.gz
python3 main.py cbc-test-set-master/bab6.mps.gz
python3 main.py cbc-test-set-master/bacasp.mps.gz
python3 main.py cbc-test-set-master/b-ball.mps.gz
python3 main.py cbc-test-set-master/beavma.mps.gz
python3 main.py cbc-test-set-master/bell5.mps.gz
python3 main.py cbc-test-set-master/berlin_5_8_0.mps.gz
python3 main.py cbc-test-set-master/bg512142.mps.gz
python3 main.py cbc-test-set-master/biella1.mps.gz
python3 main.py cbc-test-set-master/bienst1.mps.gz
python3 main.py cbc-test-set-master/binkar10_1.mps.gz
python3 main.py cbc-test-set-master/bjorn1.mps.gz
python3 main.py cbc-test-set-master/bl15_t.mps.gz
python3 main.py cbc-test-set-master/blend2.mps.gz
python3 main.py cbc-test-set-master/bley_xl1.mps.gz
python3 main.py cbc-test-set-master/blp-ar98.mps.gz
python3 main.py cbc-test-set-master/blp-ic97.mps.gz
python3 main.py cbc-test-set-master/blp-ic98.mps.gz
python3 main.py cbc-test-set-master/blp-ir98.mps.gz
python3 main.py cbc-test-set-master/BMOIPR2.mps.gz
python3 main.py cbc-test-set-master/bnatt400.mps.gz
python3 main.py cbc-test-set-master/bppc4-08.mps.gz
python3 main.py cbc-test-set-master/bppc6-02.mps.gz
python3 main.py cbc-test-set-master/bppc6-06.mps.gz
python3 main.py cbc-test-set-master/bppc8-02.mps.gz
python3 main.py cbc-test-set-master/bppc8-09.mps.gz
python3 main.py cbc-test-set-master/br1.mps.gz
python3 main.py cbc-test-set-master/br3.mps.gz
python3 main.py cbc-test-set-master/br5.mps.gz
python3 main.py cbc-test-set-master/brasil.mps.gz
python3 main.py cbc-test-set-master/BrazilInstance2.mps.gz
python3 main.py cbc-test-set-master/buildingenergy.mps.gz
python3 main.py cbc-test-set-master/c10400.mps.gz
python3 main.py cbc-test-set-master/c20400.mps.gz
python3 main.py cbc-test-set-master/cap6000.mps.gz
python3 main.py cbc-test-set-master/cargo_07.mps.gz
python3 main.py cbc-test-set-master/cdc7-4-3-2.mps.gz
python3 main.py cbc-test-set-master/cdma.mps.gz
python3 main.py cbc-test-set-master/check_features.py
python3 main.py cbc-test-set-master/chromaticindex1024-7.mps.gz
python3 main.py cbc-test-set-master/chromaticindex128-5.mps.gz
python3 main.py cbc-test-set-master/chromaticindex512-7.mps.gz
python3 main.py cbc-test-set-master/circ10-3.mps.gz
python3 main.py cbc-test-set-master/ci-s4.mps.gz
python3 main.py cbc-test-set-master/cl_06_020_03.mps.gz
python3 main.py cbc-test-set-master/cl_06_020_09.mps.gz
python3 main.py cbc-test-set-master/cl_08_020_01.mps.gz
python3 main.py cbc-test-set-master/cl_08_020_03.mps.gz
python3 main.py cbc-test-set-master/cl_08_020_04.mps.gz
python3 main.py cbc-test-set-master/cl_08_020_06.mps.gz
python3 main.py cbc-test-set-master/cl_08_020_07.mps.gz
python3 main.py cbc-test-set-master/cl_08_020_10.mps.gz
python3 main.py cbc-test-set-master/cmflsp40-36-2-10.mps.gz
python3 main.py cbc-test-set-master/cmflsp50-24-8-8.mps.gz
python3 main.py cbc-test-set-master/co-100.mps.gz
python3 main.py cbc-test-set-master/cod105.mps.gz
python3 main.py cbc-test-set-master/comp05_2idx.mps.gz
python3 main.py cbc-test-set-master/comp07_3idx.mps.gz
python3 main.py cbc-test-set-master/comp09_3idx.mps.gz
python3 main.py cbc-test-set-master/comp11_2idx.mps.gz
python3 main.py cbc-test-set-master/comp12_3idx.mps.gz
python3 main.py cbc-test-set-master/comp18_2idx.mps.gz
python3 main.py cbc-test-set-master/compact_abz5.mps.gz
python3 main.py cbc-test-set-master/core2536-691.mps.gz
python3 main.py cbc-test-set-master/core2586-950.mps.gz
python3 main.py cbc-test-set-master/core4284-1064.mps.gz
python3 main.py cbc-test-set-master/core4872-1529.mps.gz
python3 main.py cbc-test-set-master/cost266-UUE.mps.gz
python3 main.py cbc-test-set-master/cov1075.mps.gz
python3 main.py cbc-test-set-master/cryptanalysiskb128n5obj16.mps.gz
python3 main.py cbc-test-set-master/csched008.mps.gz
python3 main.py cbc-test-set-master/csched010.mps.gz
python3 main.py cbc-test-set-master/cvs16r128-89.mps.gz
python3 main.py cbc-test-set-master/cvs16r70-62.mps.gz
python3 main.py cbc-test-set-master/d10200.mps.gz
python3 main.py cbc-test-set-master/d801600.mps.gz
python3 main.py cbc-test-set-master/da_BPWC_3_8_4.mps.gz
python3 main.py cbc-test-set-master/da_BPWC_3_8_4_pp.mps.gz
python3 main.py cbc-test-set-master/dale_L1-CTA.mps.gz
python3 main.py cbc-test-set-master/dano3_5.mps.gz
python3 main.py cbc-test-set-master/dano3mip.mps.gz
python3 main.py cbc-test-set-master/danoint.mps.gz
python3 main.py cbc-test-set-master/datt256.mps.gz
python3 main.py cbc-test-set-master/dc1c.mps.gz
python3 main.py cbc-test-set-master/dc1l.mps.gz
python3 main.py cbc-test-set-master/dcmst_v20a50d4.mps.gz
python3 main.py cbc-test-set-master/dcmulti.mps.gz
python3 main.py cbc-test-set-master/decomp1.mps.gz
python3 main.py cbc-test-set-master/del.py
python3 main.py cbc-test-set-master/dfn-bwin-DBE.mps.gz
python3 main.py cbc-test-set-master/dfn-gwin-UUM.mps.gz
python3 main.py cbc-test-set-master/dg012142.mps.gz
python3 main.py cbc-test-set-master/disctom.mps.gz
python3 main.py cbc-test-set-master/dolom1.mps.gz
python3 main.py cbc-test-set-master/draw-gemcutter.mps.gz
python3 main.py cbc-test-set-master/draw-product.mps.gz
python3 main.py cbc-test-set-master/drayage-25-27.mps.gz
python3 main.py cbc-test-set-master/ds-big.mps.gz
python3 main.py cbc-test-set-master/dsbmip.mps.gz
python3 main.py cbc-test-set-master/ds.mps.gz
python3 main.py cbc-test-set-master/dt_optimization.mps.gz
python3 main.py cbc-test-set-master/dws012-03.mps.gz
python3 main.py cbc-test-set-master/e20100.mps.gz
python3 main.py cbc-test-set-master/e40400.mps.gz
python3 main.py cbc-test-set-master/eil33-2.mps.gz
python3 main.py cbc-test-set-master/eilA101-2.mps.gz
python3 main.py cbc-test-set-master/eilA76.mps.gz
python3 main.py cbc-test-set-master/eilB101.2.mps.gz
python3 main.py cbc-test-set-master/eilB101.mps.gz
python3 main.py cbc-test-set-master/eilB76.mps.gz
python3 main.py cbc-test-set-master/eilC76-2.mps.gz
python3 main.py cbc-test-set-master/eilC76.mps.gz
python3 main.py cbc-test-set-master/eilD76.2.mps.gz
python3 main.py cbc-test-set-master/eilD76.mps.gz
python3 main.py cbc-test-set-master/ej.mps.gz
python3 main.py cbc-test-set-master/enigma.mps.gz
python3 main.py cbc-test-set-master/enlight14.mps.gz
python3 main.py cbc-test-set-master/enlight_hard.mps.gz
python3 main.py cbc-test-set-master/ensemble1.mps.gz
python3 main.py cbc-test-set-master/erd_FMAS12_1st_phase.mps.gz
python3 main.py cbc-test-set-master/etDecsiDeenpDeeltEa.mps.gz
python3 main.py cbc-test-set-master/eva1aprime5x5opt.mps.gz
python3 main.py cbc-test-set-master/eva1aprime6x6opt.mps.gz
python3 main.py cbc-test-set-master/ex1010-pi.mps.gz
python3 main.py cbc-test-set-master/ex10.mps.gz
python3 main.py cbc-test-set-master/ex9.mps.gz
python3 main.py cbc-test-set-master/exp-1-500-5-5.mps.gz
python3 main.py cbc-test-set-master/f2000.mps.gz
python3 main.py cbc-test-set-master/f2gap201600.mps.gz
python3 main.py cbc-test-set-master/f2gap401600.mps.gz
python3 main.py cbc-test-set-master/f2gap40400.mps.gz
python3 main.py cbc-test-set-master/f2gap801600.mps.gz
python3 main.py cbc-test-set-master/fast0507.mps.gz
python3 main.py cbc-test-set-master/fastxgemm-n2r6s0t2.mps.gz
python3 main.py cbc-test-set-master/fastxgemm-n3r22s4t6.mps.gz
python3 main.py cbc-test-set-master/features.csv
python3 main.py cbc-test-set-master/fhnw-binpack4-4.mps.gz
python3 main.py cbc-test-set-master/fhnw-binpack4-77.mps.gz
python3 main.py cbc-test-set-master/fhnw-binschedule0.mps.gz
python3 main.py cbc-test-set-master/fhnw-binschedule2.mps.gz
python3 main.py cbc-test-set-master/fhnw-schedule-paira100.mps.gz
python3 main.py cbc-test-set-master/fhnw-schedule-paira400.mps.gz
python3 main.py cbc-test-set-master/fhnw-schedule-pairb200.mps.gz
python3 main.py cbc-test-set-master/fhnw-schedule-pairb400.mps.gz
python3 main.py cbc-test-set-master/fhnw-schedule-slot-200.mps.gz
python3 main.py cbc-test-set-master/fhnw-sq2.mps.gz
python3 main.py cbc-test-set-master/fiball.mps.gz
python3 main.py cbc-test-set-master/fiber.mps.gz
python3 main.py cbc-test-set-master/fixnet6.mps.gz
python3 main.py cbc-test-set-master/flugpl.mps.gz
python3 main.py cbc-test-set-master/Forum-21b6b8af-1736-4383-aa06-634a568ed3f5.mps.gz
python3 main.py cbc-test-set-master/Forum-e7dc26bf-753c-4e8e-a07b-63d9a200bc58.mps.gz
python3 main.py cbc-test-set-master/g.31.8.mps.gz
python3 main.py cbc-test-set-master/gen-ip002.mps.gz
python3 main.py cbc-test-set-master/gen_ip_003.mps.gz
python3 main.py cbc-test-set-master/gen_ip_005.mps.gz
python3 main.py cbc-test-set-master/gen-ip016.mps.gz
python3 main.py cbc-test-set-master/gen_ip_017.mps.gz
python3 main.py cbc-test-set-master/gen_ip_018.mps.gz
python3 main.py cbc-test-set-master/gen_ip_023.mps.gz
python3 main.py cbc-test-set-master/gen_ip_024.mps.gz
python3 main.py cbc-test-set-master/gen_ip_025.mps.gz
python3 main.py cbc-test-set-master/gen_ip_026.mps.gz
python3 main.py cbc-test-set-master/gen_ip_027.mps.gz
python3 main.py cbc-test-set-master/gen_ip_028.mps.gz
python3 main.py cbc-test-set-master/gen_ip_029.mps.gz
python3 main.py cbc-test-set-master/gen_ip_031.mps.gz
python3 main.py cbc-test-set-master/gen_ip_032.mps.gz
python3 main.py cbc-test-set-master/gen_ip_034.mps.gz
python3 main.py cbc-test-set-master/gen_ip_035.mps.gz
python3 main.py cbc-test-set-master/gen-ip036.mps.gz
python3 main.py cbc-test-set-master/gen_ip_037.mps.gz
python3 main.py cbc-test-set-master/gen_ip_038.mps.gz
python3 main.py cbc-test-set-master/gen_ip_039.mps.gz
python3 main.py cbc-test-set-master/gen_ip_040.mps.gz
python3 main.py cbc-test-set-master/gen_ip_041.mps.gz
python3 main.py cbc-test-set-master/gen_ip_042.mps.gz
python3 main.py cbc-test-set-master/gen_ip_046.mps.gz
python3 main.py cbc-test-set-master/gen_ip_050.mps.gz
python3 main.py cbc-test-set-master/gen_ip_052.mps.gz
python3 main.py cbc-test-set-master/gen-ip054.mps.gz
python3 main.py cbc-test-set-master/gen_ip_056.mps.gz
python3 main.py cbc-test-set-master/gen_ip_058.mps.gz
python3 main.py cbc-test-set-master/gen_ip_059.mps.gz
python3 main.py cbc-test-set-master/gen_ip_062.mps.gz
python3 main.py cbc-test-set-master/gen_ip_066.mps.gz
python3 main.py cbc-test-set-master/gen_ip_068.mps.gz
python3 main.py cbc-test-set-master/gen_ip_071.mps.gz
python3 main.py cbc-test-set-master/gen_ip_072.mps.gz
python3 main.py cbc-test-set-master/gen_ip_076.mps.gz
python3 main.py cbc-test-set-master/gen_ip_077.mps.gz
python3 main.py cbc-test-set-master/gen_ip_080.mps.gz
python3 main.py cbc-test-set-master/gen_ip_081.mps.gz
python3 main.py cbc-test-set-master/gen.mps.gz
python3 main.py cbc-test-set-master/genus-sym-g62-2.mps.gz
python3 main.py cbc-test-set-master/ger50-17-ptp-pop-3t.mps.gz
python3 main.py cbc-test-set-master/ger50-17-trans-pop-3t.mps.gz
python3 main.py cbc-test-set-master/germanrr.mps.gz
python3 main.py cbc-test-set-master/germany50-DBM.mps.gz
python3 main.py cbc-test-set-master/gesa2-o.mps.gz
python3 main.py cbc-test-set-master/gesa3.mps.gz
python3 main.py cbc-test-set-master/gfd-schedulen180f7d50m30k18.mps.gz
python3 main.py cbc-test-set-master/glass4.mps.gz
python3 main.py cbc-test-set-master/glass-sc.mps.gz
python3 main.py cbc-test-set-master/gmu-35-40.mps.gz
python3 main.py cbc-test-set-master/gmu-35-50.mps.gz
python3 main.py cbc-test-set-master/gmut-75-50.mps.gz
python3 main.py cbc-test-set-master/gmut-76-50.mps.gz
python3 main.py cbc-test-set-master/gmut-77-40.mps.gz
python3 main.py cbc-test-set-master/go19.mps.gz
python3 main.py cbc-test-set-master/gr4x6.mps.gz
python3 main.py cbc-test-set-master/graph20-20-1rand.mps.gz
python3 main.py cbc-test-set-master/graph40-20-1rand.mps.gz
python3 main.py cbc-test-set-master/graph40-40-1rand.mps.gz
python3 main.py cbc-test-set-master/graph40-80-1rand.mps.gz
python3 main.py cbc-test-set-master/graphdraw-domain.mps.gz
python3 main.py cbc-test-set-master/graphdraw-gemcutter.mps.gz
python3 main.py cbc-test-set-master/graphdraw-grafo2.mps.gz
python3 main.py cbc-test-set-master/gsvm2rl3.mps.gz
python3 main.py cbc-test-set-master/gsvm2rl5.mps.gz
python3 main.py cbc-test-set-master/gt2.mps.gz
python3 main.py cbc-test-set-master/gurobi.log
python3 main.py cbc-test-set-master/gus-sch.mps.gz
python3 main.py cbc-test-set-master/h80x6320.mps.gz
python3 main.py cbc-test-set-master/hanoi5.mps.gz
python3 main.py cbc-test-set-master/haprp.mps.gz
python3 main.py cbc-test-set-master/harp2.mps.gz
python3 main.py cbc-test-set-master/hgms30.mps.gz
python3 main.py cbc-test-set-master/hgms62.mps.gz
python3 main.py cbc-test-set-master/hgms-det.mps.gz
python3 main.py cbc-test-set-master/highschool1-aigio.mps.gz
python3 main.py cbc-test-set-master/hypothyroid-k1.mps.gz
python3 main.py cbc-test-set-master/ibarra.mps.gz
python3 main.py cbc-test-set-master/ic97_potential.mps.gz
python3 main.py cbc-test-set-master/ic97_tension.mps.gz
python3 main.py cbc-test-set-master/icir97_tension.mps.gz
python3 main.py cbc-test-set-master/iis-100-0-cov.mps.gz
python3 main.py cbc-test-set-master/iis-bupa-cov.mps.gz
python3 main.py cbc-test-set-master/iis-hc-cov.mps.gz
python3 main.py cbc-test-set-master/iis-pima-cov.mps.gz
python3 main.py cbc-test-set-master/irish-electricity.mps.gz
python3 main.py cbc-test-set-master/irp.mps.gz
python3 main.py cbc-test-set-master/istanbul-no-cutoff.mps.gz
python3 main.py cbc-test-set-master/ivu06-big.mps.gz
python3 main.py cbc-test-set-master/ivu06.mps.gz
python3 main.py cbc-test-set-master/ivu52.mps.gz
python3 main.py cbc-test-set-master/j12016_10_cuts.mps.gz
python3 main.py cbc-test-set-master/j12016_10.mps.gz
python3 main.py cbc-test-set-master/j12048_7.mps.gz
python3 main.py cbc-test-set-master/j12052_10.mps.gz
python3 main.py cbc-test-set-master/j3014_5.mps.gz
python3 main.py cbc-test-set-master/j3041_1.mps.gz
python3 main.py cbc-test-set-master/j3047_2.mps.gz
python3 main.py cbc-test-set-master/j3050_8.mps.gz
python3 main.py cbc-test-set-master/j6029_7.mps.gz
python3 main.py cbc-test-set-master/j9025_10.mps.gz
python3 main.py cbc-test-set-master/j9025_6.mps.gz
python3 main.py cbc-test-set-master/j905_8.mps.gz
python3 main.py cbc-test-set-master/janos-us-DDM.mps.gz
python3 main.py cbc-test-set-master/k1mushroom.mps.gz
python3 main.py cbc-test-set-master/keller4cpart.mps.gz
python3 main.py cbc-test-set-master/keller4cpartpp.mps.gz
python3 main.py cbc-test-set-master/khb05250.mps.gz
python3 main.py cbc-test-set-master/kosova1.mps.gz
python3 main.py cbc-test-set-master/l152lav.mps.gz
python3 main.py cbc-test-set-master/l2p12.mps.gz
python3 main.py cbc-test-set-master/layer2.mps.gz
python3 main.py cbc-test-set-master/layer3.mps.gz
python3 main.py cbc-test-set-master/layer4.mps.gz
python3 main.py cbc-test-set-master/layer.mps.gz
python3 main.py cbc-test-set-master/lectsched-4-obj.mps.gz
python3 main.py cbc-test-set-master/leo1.mps.gz
python3 main.py cbc-test-set-master/leo2.mps.gz
python3 main.py cbc-test-set-master/liu.mps.gz
python3 main.py cbc-test-set-master/long05_j.mps.gz
python3 main.py cbc-test-set-master/long_hidden01_j.mps.gz
python3 main.py cbc-test-set-master/loopha13.mps.gz
python3 main.py cbc-test-set-master/lotsize.mps.gz
python3 main.py cbc-test-set-master/LpPackingModel2_Dim10.mps.gz
python3 main.py cbc-test-set-master/LpPackingModel5_Dim15.mps.gz
python3 main.py cbc-test-set-master/lr1dr02vc05v8a-t360.mps.gz
python3 main.py cbc-test-set-master/LR1_DR03_VC03_V10b_t360.mps.gz
python3 main.py cbc-test-set-master/LR1_DR08_VC10_V40a_t120.mps.gz
python3 main.py cbc-test-set-master/lr1dr12vc10v70b-t360.mps.gz
python3 main.py cbc-test-set-master/LR2_11_DR2_33_VC4_V11a_t60.mps.gz
python3 main.py cbc-test-set-master/LR2_22_DR3_333_VC4_V14a_t60.mps.gz
python3 main.py cbc-test-set-master/lrsa120.mps.gz
python3 main.py cbc-test-set-master/lseu.mps.gz
python3 main.py cbc-test-set-master/m100n500k4r1.mps.gz
python3 main.py cbc-test-set-master/mad.mps.gz
python3 main.py cbc-test-set-master/manna81.mps.gz
python3 main.py cbc-test-set-master/map10.mps.gz
python3 main.py cbc-test-set-master/markshare2.mps.gz
python3 main.py cbc-test-set-master/markshare_4_0.mps.gz
python3 main.py cbc-test-set-master/markshare_5_0.mps.gz
python3 main.py cbc-test-set-master/mas74.mps.gz
python3 main.py cbc-test-set-master/mas76.mps.gz
python3 main.py cbc-test-set-master/maxgasflow.mps.gz
python3 main.py cbc-test-set-master/mc11.mps.gz
python3 main.py cbc-test-set-master/mcsched.mps.gz
python3 main.py cbc-test-set-master/medium_hint02_j.mps.gz
python3 main.py cbc-test-set-master/methanosarcina.mps.gz
python3 main.py cbc-test-set-master/mik-250-1-100-1.mps.gz
python3 main.py cbc-test-set-master/mik-250-20-75-3.mps.gz
python3 main.py cbc-test-set-master/milo-v12-6-r1-75-1.mps.gz
python3 main.py cbc-test-set-master/milo-v13-4-3d-4-0.mps.gz
python3 main.py cbc-test-set-master/mine-90-10.mps.gz
python3 main.py cbc-test-set-master/mining.mps.gz
python3 main.py cbc-test-set-master/minuteddispatchstrategy.mps.gz
python3 main.py cbc-test-set-master/misc03.mps.gz
python3 main.py cbc-test-set-master/misc06.mps.gz
python3 main.py cbc-test-set-master/misc07.mps.gz
python3 main.py cbc-test-set-master/mitre.mps.gz
python3 main.py cbc-test-set-master/mkc1.mps.gz
python3 main.py cbc-test-set-master/mkc.mps.gz
python3 main.py cbc-test-set-master/m-minas196.mps.gz
python3 main.py cbc-test-set-master/mod008.mps.gz
python3 main.py cbc-test-set-master/mod010.mps.gz
python3 main.py cbc-test-set-master/mod011.mps.gz
python3 main.py cbc-test-set-master/modglob.mps.gz
python3 main.py cbc-test-set-master/momentum1.mps.gz
python3 main.py cbc-test-set-master/momentum3.mps.gz
python3 main.py cbc-test-set-master/monks-2.test.sc.mps.gz
python3 main.py cbc-test-set-master/monks-2.train.sc.mps.gz
python3 main.py cbc-test-set-master/msc98-ip.mps.gz
python3 main.py cbc-test-set-master/mtest4ma.mps.gz
python3 main.py cbc-test-set-master/mushroom-best.mps.gz
python3 main.py cbc-test-set-master/mzzv11.mps.gz
python3 main.py cbc-test-set-master/mzzv42z.mps.gz
python3 main.py cbc-test-set-master/n080w8-1.mps.gz
python3 main.py cbc-test-set-master/n13-3.mps.gz
python3 main.py cbc-test-set-master/n15-3.mps.gz
python3 main.py cbc-test-set-master/n2seq36f.mps.gz
python3 main.py cbc-test-set-master/n2seq36q.mps.gz
python3 main.py cbc-test-set-master/n3-3.mps.gz
python3 main.py cbc-test-set-master/n3705.mps.gz
python3 main.py cbc-test-set-master/n3div36.mps.gz
python3 main.py cbc-test-set-master/n3seq24.mps.gz
python3 main.py cbc-test-set-master/n4-3.mps.gz
python3 main.py cbc-test-set-master/n5-3.mps.gz
python3 main.py cbc-test-set-master/n6-3.mps.gz
python3 main.py cbc-test-set-master/n7-3.mps.gz
python3 main.py cbc-test-set-master/n9-3.mps.gz
python3 main.py cbc-test-set-master/nag.mps.gz
python3 main.py cbc-test-set-master/nb10tb.mps.gz
python3 main.py cbc-test-set-master/neos-1067731.mps.gz
python3 main.py cbc-test-set-master/neos-1096528.mps.gz
python3 main.py cbc-test-set-master/neos10.mps.gz
python3 main.py cbc-test-set-master/neos-1109824.mps.gz
python3 main.py cbc-test-set-master/neos-1122047.mps.gz
python3 main.py cbc-test-set-master/neos-1140050.mps.gz
python3 main.py cbc-test-set-master/neos-1171448.mps.gz
python3 main.py cbc-test-set-master/neos-1171737.mps.gz
python3 main.py cbc-test-set-master/neos-1215891.mps.gz
python3 main.py cbc-test-set-master/neos-1223462.mps.gz
python3 main.py cbc-test-set-master/neos-1224597.mps.gz
python3 main.py cbc-test-set-master/neos-1281048.mps.gz
python3 main.py cbc-test-set-master/neos-1311124.mps.gz
python3 main.py cbc-test-set-master/neos-1324574.mps.gz
python3 main.py cbc-test-set-master/neos-1330346.mps.gz
python3 main.py cbc-test-set-master/neos-1337307.mps.gz
python3 main.py cbc-test-set-master/neos-1354092.mps.gz
python3 main.py cbc-test-set-master/neos-1367061.mps.gz
python3 main.py cbc-test-set-master/neos-1396125.mps.gz
python3 main.py cbc-test-set-master/neos13.mps.gz
python3 main.py cbc-test-set-master/neos-1420546.mps.gz
python3 main.py cbc-test-set-master/neos-1420790.mps.gz
python3 main.py cbc-test-set-master/neos-1423785.mps.gz
python3 main.py cbc-test-set-master/neos-1425699.mps.gz
python3 main.py cbc-test-set-master/neos-1429212.mps.gz
python3 main.py cbc-test-set-master/neos-1437164.mps.gz
python3 main.py cbc-test-set-master/neos-1440225.mps.gz
python3 main.py cbc-test-set-master/neos-1441553.mps.gz
python3 main.py cbc-test-set-master/neos-1442119.mps.gz
python3 main.py cbc-test-set-master/neos-1445532.mps.gz
python3 main.py cbc-test-set-master/neos-1445738.mps.gz
python3 main.py cbc-test-set-master/neos-1456979.mps.gz
python3 main.py cbc-test-set-master/neos-1516309.mps.gz
python3 main.py cbc-test-set-master/neos-1582420.mps.gz
python3 main.py cbc-test-set-master/neos-1593097.mps.gz
python3 main.py cbc-test-set-master/neos-1595230.mps.gz
python3 main.py cbc-test-set-master/neos-1597104.mps.gz
python3 main.py cbc-test-set-master/neos-1599274.mps.gz
python3 main.py cbc-test-set-master/neos-1601936.mps.gz
python3 main.py cbc-test-set-master/neos-1605061.mps.gz
python3 main.py cbc-test-set-master/neos-1620770.mps.gz
python3 main.py cbc-test-set-master/neos-1620807.mps.gz
python3 main.py cbc-test-set-master/neos16.mps.gz
python3 main.py cbc-test-set-master/neos17.mps.gz
python3 main.py cbc-test-set-master/neos18.mps.gz
python3 main.py cbc-test-set-master/neos1.mps.gz
python3 main.py cbc-test-set-master/neos-2075418-temuka.mps.gz
python3 main.py cbc-test-set-master/neos22.mps.gz
python3 main.py cbc-test-set-master/neos-2328163-agri.mps.gz
python3 main.py cbc-test-set-master/neos-2629914-sudost.mps.gz
python3 main.py cbc-test-set-master/neos-2652786-brda.mps.gz
python3 main.py cbc-test-set-master/neos-2657525-crna.mps.gz
python3 main.py cbc-test-set-master/neos-2669500-cust.mps.gz
python3 main.py cbc-test-set-master/neos-2746589-doon.mps.gz
python3 main.py cbc-test-set-master/neos-2978193-inde.mps.gz
python3 main.py cbc-test-set-master/neos-2978205-isar.mps.gz
python3 main.py cbc-test-set-master/neos-2987310-joes.mps.gz
python3 main.py cbc-test-set-master/neos-2991472-kalu.mps.gz
python3 main.py cbc-test-set-master/neos2.mps.gz
python3 main.py cbc-test-set-master/neos2.sol
python3 main.py cbc-test-set-master/neos-3004026-krka.mps.gz
python3 main.py cbc-test-set-master/neos-3009394-lami.mps.gz
python3 main.py cbc-test-set-master/neos-3024952-loue.mps.gz
python3 main.py cbc-test-set-master/neos-3025225-shelon.mps.gz
python3 main.py cbc-test-set-master/neos-3045796-mogo.mps.gz
python3 main.py cbc-test-set-master/neos-3046615-murg.mps.gz
python3 main.py cbc-test-set-master/neos-3072252-nete.mps.gz
python3 main.py cbc-test-set-master/neos-3083819-nubu.mps.gz
python3 main.py cbc-test-set-master/neos-3116779-oban.mps.gz
python3 main.py cbc-test-set-master/neos-3118745-obra.mps.gz
python3 main.py cbc-test-set-master/neos-3148108-pahi.mps.gz
python3 main.py cbc-test-set-master/neos-3209462-rhin.mps.gz
python3 main.py cbc-test-set-master/neos-3209519-ruhr.mps.gz
python3 main.py cbc-test-set-master/neos-3214367-sovi.mps.gz
python3 main.py cbc-test-set-master/neos-3216931-puriri.mps.gz
python3 main.py cbc-test-set-master/neos-3226448-wkra.mps.gz
python3 main.py cbc-test-set-master/neos-3237086-abava.mps.gz
python3 main.py cbc-test-set-master/neos-3322547-alsek.mps.gz
python3 main.py cbc-test-set-master/neos-3352863-ancoa.mps.gz
python3 main.py cbc-test-set-master/neos-3354841-apure.mps.gz
python3 main.py cbc-test-set-master/neos-3355323-arnon.mps.gz
python3 main.py cbc-test-set-master/neos-3372571-onahau.mps.gz
python3 main.py cbc-test-set-master/neos-3381206-awhea.mps.gz
python3 main.py cbc-test-set-master/neos-3402294-bobin.mps.gz
python3 main.py cbc-test-set-master/neos-3402454-bohle.mps.gz
python3 main.py cbc-test-set-master/neos-3426085-ticino.mps.gz
python3 main.py cbc-test-set-master/neos-3426132-dieze.mps.gz
python3 main.py cbc-test-set-master/neos-3437289-erdre.mps.gz
python3 main.py cbc-test-set-master/neos-3530905-gaula.mps.gz
python3 main.py cbc-test-set-master/neos-3555904-turama.mps.gz
python3 main.py cbc-test-set-master/neos-3572885-glina.mps.gz
python3 main.py cbc-test-set-master/neos-3581454-haast.mps.gz
python3 main.py cbc-test-set-master/neos-3594536-henty.mps.gz
python3 main.py cbc-test-set-master/neos-3603137-hoteo.mps.gz
python3 main.py cbc-test-set-master/neos-3610051-istra.mps.gz
python3 main.py cbc-test-set-master/neos-3611689-kaihu.mps.gz
python3 main.py cbc-test-set-master/neos-3627168-kasai.mps.gz
python3 main.py cbc-test-set-master/neos-3634244-kauru.mps.gz
python3 main.py cbc-test-set-master/neos-3660371-kurow.mps.gz
python3 main.py cbc-test-set-master/neos-3665875-lesum.mps.gz
python3 main.py cbc-test-set-master/neos-3682128-sandon.mps.gz
python3 main.py cbc-test-set-master/neos-3691541-lonja.mps.gz
python3 main.py cbc-test-set-master/neos-3695882-vesdre.mps.gz
python3 main.py cbc-test-set-master/neos-3696678-lyvia.mps.gz
python3 main.py cbc-test-set-master/neos-3754224-navua.mps.gz
python3 main.py cbc-test-set-master/neos-3754480-nidda.mps.gz
python3 main.py cbc-test-set-master/neos-3755335-nizao.mps.gz
python3 main.py cbc-test-set-master/neos-3759587-noosa.mps.gz
python3 main.py cbc-test-set-master/neos-3988577-wolgan.mps.gz
python3 main.py cbc-test-set-master/neos-4165869-wannon.mps.gz
python3 main.py cbc-test-set-master/neos-4292145-piako.mps.gz
python3 main.py cbc-test-set-master/neos-4295773-pissa.mps.gz
python3 main.py cbc-test-set-master/neos-4300652-rahue.mps.gz
python3 main.py cbc-test-set-master/neos-4306827-ravan.mps.gz
python3 main.py cbc-test-set-master/neos-4321076-ruwer.mps.gz
python3 main.py cbc-test-set-master/neos-4322846-ryton.mps.gz
python3 main.py cbc-test-set-master/neos-4333464-siret.mps.gz
python3 main.py cbc-test-set-master/neos-4333596-skien.mps.gz
python3 main.py cbc-test-set-master/neos-4338804-snowy.mps.gz
python3 main.py cbc-test-set-master/neos-4343293-stony.mps.gz
python3 main.py cbc-test-set-master/neos-4355351-swalm.mps.gz
python3 main.py cbc-test-set-master/neos-4359986-taipa.mps.gz
python3 main.py cbc-test-set-master/neos-4360552-sangro.mps.gz
python3 main.py cbc-test-set-master/neos-4391920-timok.mps.gz
python3 main.py cbc-test-set-master/neos-4408804-prosna.mps.gz
python3 main.py cbc-test-set-master/neos-4409277-trave.mps.gz
python3 main.py cbc-test-set-master/neos-4413714-turia.mps.gz
python3 main.py cbc-test-set-master/neos-4532248-waihi.mps.gz
python3 main.py cbc-test-set-master/neos-4533806-waima.mps.gz
python3 main.py cbc-test-set-master/neos-4545615-waita.mps.gz
python3 main.py cbc-test-set-master/neos-4562542-watut.mps.gz
python3 main.py cbc-test-set-master/neos-4647027-thurso.mps.gz
python3 main.py cbc-test-set-master/neos-4647030-tutaki.mps.gz
python3 main.py cbc-test-set-master/neos-4647032-veleka.mps.gz
python3 main.py cbc-test-set-master/neos-4650160-yukon.mps.gz
python3 main.py cbc-test-set-master/neos-4724674-aorere.mps.gz
python3 main.py cbc-test-set-master/neos-4736745-arroux.mps.gz
python3 main.py cbc-test-set-master/neos-4738912-atrato.mps.gz
python3 main.py cbc-test-set-master/neos-4754521-awarau.mps.gz
python3 main.py cbc-test-set-master/neos-4760493-puerua.mps.gz
python3 main.py cbc-test-set-master/neos-476283.mps.gz
python3 main.py cbc-test-set-master/neos-4797081-pakoka.mps.gz
python3 main.py cbc-test-set-master/neos-4805882-barwon.mps.gz
python3 main.py cbc-test-set-master/neos-480878.mps.gz
python3 main.py cbc-test-set-master/neos-4954274-beardy.mps.gz
python3 main.py cbc-test-set-master/neos-4954672-berkel.mps.gz
python3 main.py cbc-test-set-master/neos-4966258-blicks.mps.gz
python3 main.py cbc-test-set-master/neos-4976951-bunnoo.mps.gz
python3 main.py cbc-test-set-master/neos-498623.mps.gz
python3 main.py cbc-test-set-master/neos-503737.mps.gz
python3 main.py cbc-test-set-master/neos-5041822-cockle.mps.gz
python3 main.py cbc-test-set-master/neos-5044663-wairoa.mps.gz
python3 main.py cbc-test-set-master/neos-5045105-creuse.mps.gz
python3 main.py cbc-test-set-master/neos-5049753-cuanza.mps.gz
python3 main.py cbc-test-set-master/neos-5051588-culgoa.mps.gz
python3 main.py cbc-test-set-master/neos-5052403-cygnet.mps.gz
python3 main.py cbc-test-set-master/neos-506428.mps.gz
python3 main.py cbc-test-set-master/neos-5075914-elvire.mps.gz
python3 main.py cbc-test-set-master/neos-5078479-escaut.mps.gz
python3 main.py cbc-test-set-master/neos-5083528-gimone.mps.gz
python3 main.py cbc-test-set-master/neos-5093327-huahum.mps.gz
python3 main.py cbc-test-set-master/neos-5102383-irwell.mps.gz
python3 main.py cbc-test-set-master/neos-5104907-jarama.mps.gz
python3 main.py cbc-test-set-master/neos-5106984-jizera.mps.gz
python3 main.py cbc-test-set-master/neos-5107597-kakapo.mps.gz
python3 main.py cbc-test-set-master/neos-5114902-kasavu.mps.gz
python3 main.py cbc-test-set-master/neos-5116085-kenana.mps.gz
python3 main.py cbc-test-set-master/neos-5123665-limmat.mps.gz
python3 main.py cbc-test-set-master/neos-5125849-lopori.mps.gz
python3 main.py cbc-test-set-master/neos-5129192-manaia.mps.gz
python3 main.py cbc-test-set-master/neos-5138690-middle.mps.gz
python3 main.py cbc-test-set-master/neos-5140963-mincio.mps.gz
python3 main.py cbc-test-set-master/neos-5149806-wieprz.mps.gz
python3 main.py cbc-test-set-master/neos-5178119-nalagi.mps.gz
python3 main.py cbc-test-set-master/neos-5182409-nasivi.mps.gz
python3 main.py cbc-test-set-master/neos-5188808-nattai.mps.gz
python3 main.py cbc-test-set-master/neos-5189128-totara.mps.gz
python3 main.py cbc-test-set-master/neos-5192052-neckar.mps.gz
python3 main.py cbc-test-set-master/neos-5195221-niemur.mps.gz
python3 main.py cbc-test-set-master/neos-5196530-nuhaka.mps.gz
python3 main.py cbc-test-set-master/neos-5221106-oparau.mps.gz
python3 main.py cbc-test-set-master/neos-5223573-tarwin.mps.gz
python3 main.py cbc-test-set-master/neos-525149.mps.gz
python3 main.py cbc-test-set-master/neos-5260764-orauea.mps.gz
python3 main.py cbc-test-set-master/neos-5261882-treska.mps.gz
python3 main.py cbc-test-set-master/neos-5273874-yomtsa.mps.gz
python3 main.py cbc-test-set-master/neos-538867.mps.gz
python3 main.py cbc-test-set-master/neos-544324.mps.gz
python3 main.py cbc-test-set-master/neos-547911.mps.gz
python3 main.py cbc-test-set-master/neos-555343.mps.gz
python3 main.py cbc-test-set-master/neos-555424.mps.gz
python3 main.py cbc-test-set-master/neos-555884.mps.gz
python3 main.py cbc-test-set-master/neos-555927.mps.gz
python3 main.py cbc-test-set-master/neos-565815.mps.gz
python3 main.py cbc-test-set-master/neos-574665.mps.gz
python3 main.py cbc-test-set-master/neos-578379.mps.gz
python3 main.py cbc-test-set-master/neos-595904.mps.gz
python3 main.py cbc-test-set-master/neos5.mps.gz
python3 main.py cbc-test-set-master/neos-611135.mps.gz
python3 main.py cbc-test-set-master/neos-631517.mps.gz
python3 main.py cbc-test-set-master/neos-631694.mps.gz
python3 main.py cbc-test-set-master/neos-631710.mps.gz
python3 main.py cbc-test-set-master/neos-633273.mps.gz
python3 main.py cbc-test-set-master/neos-662469.mps.gz
python3 main.py cbc-test-set-master/neos-686190.mps.gz
python3 main.py cbc-test-set-master/neos-691058.mps.gz
python3 main.py cbc-test-set-master/neos6.mps.gz
python3 main.py cbc-test-set-master/neos-709469.mps.gz
python3 main.py cbc-test-set-master/neos-738098.mps.gz
python3 main.py cbc-test-set-master/neos-777800.mps.gz
python3 main.py cbc-test-set-master/neos-780889.mps.gz
python3 main.py cbc-test-set-master/neos-785914.mps.gz
python3 main.py cbc-test-set-master/neos-787933.mps.gz
python3 main.py cbc-test-set-master/neos-791021.mps.gz
python3 main.py cbc-test-set-master/neos-799838.mps.gz
python3 main.py cbc-test-set-master/neos-801834.mps.gz
python3 main.py cbc-test-set-master/neos-807456.mps.gz
python3 main.py cbc-test-set-master/neos-807639.mps.gz
python3 main.py cbc-test-set-master/neos-808214.mps.gz
python3 main.py cbc-test-set-master/neos-810286.mps.gz
python3 main.py cbc-test-set-master/neos-820879.mps.gz
python3 main.py cbc-test-set-master/neos-824661.mps.gz
python3 main.py cbc-test-set-master/neos-825075.mps.gz
python3 main.py cbc-test-set-master/neos-826224.mps.gz
python3 main.py cbc-test-set-master/neos-826650.mps.gz
python3 main.py cbc-test-set-master/neos-827175.mps.gz
python3 main.py cbc-test-set-master/neos-831188.mps.gz
python3 main.py cbc-test-set-master/neos-848198.mps.gz
python3 main.py cbc-test-set-master/neos-848589.mps.gz
python3 main.py cbc-test-set-master/neos-849702.mps.gz
python3 main.py cbc-test-set-master/neos-850681.mps.gz
python3 main.py cbc-test-set-master/neos859080.mps.gz
python3 main.py cbc-test-set-master/neos-859770.mps.gz
python3 main.py cbc-test-set-master/neos-860244.mps.gz
python3 main.py cbc-test-set-master/neos-860300.mps.gz
python3 main.py cbc-test-set-master/neos-872648.mps.gz
python3 main.py cbc-test-set-master/neos-876808.mps.gz
python3 main.py cbc-test-set-master/neos-885086.mps.gz
python3 main.py cbc-test-set-master/neos-885524.mps.gz
python3 main.py cbc-test-set-master/neos8.mps.gz
python3 main.py cbc-test-set-master/neos-905856.mps.gz
python3 main.py cbc-test-set-master/neos-911970.mps.gz
python3 main.py cbc-test-set-master/neos-912015.mps.gz
python3 main.py cbc-test-set-master/neos-912023.mps.gz
python3 main.py cbc-test-set-master/neos-913984.mps.gz
python3 main.py cbc-test-set-master/neos-916792.mps.gz
python3 main.py cbc-test-set-master/neos-931538.mps.gz
python3 main.py cbc-test-set-master/neos-932721.mps.gz
python3 main.py cbc-test-set-master/neos-933562.mps.gz
python3 main.py cbc-test-set-master/neos-933966.mps.gz
python3 main.py cbc-test-set-master/neos-934278.mps.gz
python3 main.py cbc-test-set-master/neos-934531.mps.gz
python3 main.py cbc-test-set-master/neos-935234.mps.gz
python3 main.py cbc-test-set-master/neos-935769.mps.gz
python3 main.py cbc-test-set-master/neos-937815.mps.gz
python3 main.py cbc-test-set-master/neos-941313.mps.gz
python3 main.py cbc-test-set-master/neos-948268.mps.gz
python3 main.py cbc-test-set-master/neos-948346.mps.gz
python3 main.py cbc-test-set-master/neos-950242.mps.gz
python3 main.py cbc-test-set-master/neos-952987.mps.gz
python3 main.py cbc-test-set-master/neos-953928.mps.gz
python3 main.py cbc-test-set-master/neos-954925.mps.gz
python3 main.py cbc-test-set-master/neos-956971.mps.gz
python3 main.py cbc-test-set-master/neos-957143.mps.gz
python3 main.py cbc-test-set-master/neos-957270.mps.gz
python3 main.py cbc-test-set-master/neos-957323.mps.gz
python3 main.py cbc-test-set-master/neos-957389.mps.gz
python3 main.py cbc-test-set-master/neos-960392.mps.gz
python3 main.py cbc-test-set-master/neos9.mps.gz
python3 main.py cbc-test-set-master/net12.mps.gz
python3 main.py cbc-test-set-master/netdiversion.mps.gz
python3 main.py cbc-test-set-master/newdano.mps.gz
python3 main.py cbc-test-set-master/nexp-150-20-1-5.mps.gz
python3 main.py cbc-test-set-master/nexp-150-20-8-5.mps.gz
python3 main.py cbc-test-set-master/nexp-50-20-4-2.mps.gz
python3 main.py cbc-test-set-master/nh97_potential.mps.gz
python3 main.py cbc-test-set-master/nh97_tension.mps.gz
python3 main.py cbc-test-set-master/nj1.mps.gz
python3 main.py cbc-test-set-master/nj3.mps.gz
python3 main.py cbc-test-set-master/noswot.mps.gz
python3 main.py cbc-test-set-master/nrc2rmn120w4_1_4-6-2-6.mps.gz
python3 main.py cbc-test-set-master/nrperfan.mps.gz
python3 main.py cbc-test-set-master/ns1111636.mps.gz
python3 main.py cbc-test-set-master/ns1116954.mps.gz
python3 main.py cbc-test-set-master/ns1208400.mps.gz
python3 main.py cbc-test-set-master/ns1430538.mps.gz
python3 main.py cbc-test-set-master/ns1456591.mps.gz
python3 main.py cbc-test-set-master/ns1631475.mps.gz
python3 main.py cbc-test-set-master/ns1644855.mps.gz
python3 main.py cbc-test-set-master/ns1663818.mps.gz
python3 main.py cbc-test-set-master/ns1688347.mps.gz
python3 main.py cbc-test-set-master/ns1690781.mps.gz
python3 main.py cbc-test-set-master/ns1696083.mps.gz
python3 main.py cbc-test-set-master/ns1758913.mps.gz
python3 main.py cbc-test-set-master/ns1760995.mps.gz
python3 main.py cbc-test-set-master/ns1766074.mps.gz
python3 main.py cbc-test-set-master/ns1778858.mps.gz
python3 main.py cbc-test-set-master/ns1828997.mps.gz
python3 main.py cbc-test-set-master/ns1830653.mps.gz
python3 main.py cbc-test-set-master/ns1849932.mps.gz
python3 main.py cbc-test-set-master/ns1853823.mps.gz
python3 main.py cbc-test-set-master/ns1854840.mps.gz
python3 main.py cbc-test-set-master/ns1856153.mps.gz
python3 main.py cbc-test-set-master/ns1904248.mps.gz
python3 main.py cbc-test-set-master/ns1905797.mps.gz
python3 main.py cbc-test-set-master/ns1952667.mps.gz
python3 main.py cbc-test-set-master/ns2071214.mps.gz
python3 main.py cbc-test-set-master/ns2124243.mps.gz
python3 main.py cbc-test-set-master/ns2137859.mps.gz
python3 main.py cbc-test-set-master/ns4-pr3.mps.gz
python3 main.py cbc-test-set-master/ns4-pr6.mps.gz
python3 main.py cbc-test-set-master/ns4-pr9.mps.gz
python3 main.py cbc-test-set-master/ns894786.mps.gz
python3 main.py cbc-test-set-master/ns903616.mps.gz
python3 main.py cbc-test-set-master/ns930473.mps.gz
python3 main.py cbc-test-set-master/nsa.mps.gz
python3 main.py cbc-test-set-master/nsr8k.mps.gz
python3 main.py cbc-test-set-master/nsrand-ipx.mps.gz
python3 main.py cbc-test-set-master/nu120-pr3.mps.gz
python3 main.py cbc-test-set-master/nu25-pr12.mps.gz
python3 main.py cbc-test-set-master/nu60-pr9.mps.gz
python3 main.py cbc-test-set-master/nug08.mps.gz
python3 main.py cbc-test-set-master/nursesched-medium04.mps.gz
python3 main.py cbc-test-set-master/nursesched-sprint02.mps.gz
python3 main.py cbc-test-set-master/nw04.mps.gz
python3 main.py cbc-test-set-master/opm2-z11-s8.mps.gz
python3 main.py cbc-test-set-master/opm2-z12-s8.mps.gz
python3 main.py cbc-test-set-master/opm2-z6-s1.mps.gz
python3 main.py cbc-test-set-master/opm2-z7-s2.mps.gz
python3 main.py cbc-test-set-master/opm2-z8-s0.mps.gz
python3 main.py cbc-test-set-master/opt1217.mps.gz
python3 main.py cbc-test-set-master/p0033.mps.gz
python3 main.py cbc-test-set-master/p0201.mps.gz
python3 main.py cbc-test-set-master/p0282.mps.gz
python3 main.py cbc-test-set-master/p0548.mps.gz
python3 main.py cbc-test-set-master/P1.mps.gz
python3 main.py cbc-test-set-master/p2756.mps.gz
python3 main.py cbc-test-set-master/p6b.mps.gz
python3 main.py cbc-test-set-master/page-blocks.pictures.sc.mps.gz
python3 main.py cbc-test-set-master/pb-fit2d.mps.gz
python3 main.py cbc-test-set-master/pb-gfrd-pnc.mps.gz
python3 main.py cbc-test-set-master/pb-grow22.mps.gz
python3 main.py cbc-test-set-master/pb-market-split8-70-4.mps.gz
python3 main.py cbc-test-set-master/pb-simp-nonunif.mps.gz
python3 main.py cbc-test-set-master/pdistuchoa.mps.gz
python3 main.py cbc-test-set-master/peg-solitaire-a3.mps.gz
python3 main.py cbc-test-set-master/pg5_34.mps.gz
python3 main.py cbc-test-set-master/pg.mps.gz
python3 main.py cbc-test-set-master/physiciansched3-4.mps.gz
python3 main.py cbc-test-set-master/physiciansched5-3.mps.gz
python3 main.py cbc-test-set-master/physiciansched6-1.mps.gz
python3 main.py cbc-test-set-master/physiciansched6-2.mps.gz
python3 main.py cbc-test-set-master/pigeon-08.mps.gz
python3 main.py cbc-test-set-master/pigeon-16.mps.gz
python3 main.py cbc-test-set-master/pima.sc.mps.gz
python3 main.py cbc-test-set-master/piperout-27.mps.gz
python3 main.py cbc-test-set-master/pk1.mps.gz
python3 main.py cbc-test-set-master/planar150_s.mps.gz
python3 main.py cbc-test-set-master/pp08aCUTS.mps.gz
python3 main.py cbc-test-set-master/pp08a.mps.gz
python3 main.py cbc-test-set-master/prob-23844-t1-0.mps.gz
python3 main.py cbc-test-set-master/prob-25581-0.mps.gz
python3 main.py cbc-test-set-master/probportfolio.mps.gz
python3 main.py cbc-test-set-master/prod1.mps.gz
python3 main.py cbc-test-set-master/prod2.mps.gz
python3 main.py cbc-test-set-master/product_1st_phase.mps.gz
python3 main.py cbc-test-set-master/proteindesign122trx11p8.mps.gz
python3 main.py cbc-test-set-master/protfold.mps.gz
python3 main.py cbc-test-set-master/pw-myciel4.mps.gz
python3 main.py cbc-test-set-master/pythago7825.mps.gz
python3 main.py cbc-test-set-master/qap10.mps.gz
python3 main.py cbc-test-set-master/qiu.mps.gz
python3 main.py cbc-test-set-master/qnet1_o.mps.gz
python3 main.py cbc-test-set-master/queens-30.mps.gz
python3 main.py cbc-test-set-master/r4l4-02-tree-bounds-50.mps.gz
python3 main.py cbc-test-set-master/r80x800.mps.gz
python3 main.py cbc-test-set-master/radiationm18-12-05.mps.gz
python3 main.py cbc-test-set-master/radiationm40-10-02.mps.gz
python3 main.py cbc-test-set-master/rail01.mps.gz
python3 main.py cbc-test-set-master/rail02.mps.gz
python3 main.py cbc-test-set-master/rail03.mps.gz
python3 main.py cbc-test-set-master/rail507.mps.gz
python3 main.py cbc-test-set-master/railway_8_1_0.mps.gz
python3 main.py cbc-test-set-master/ramos3.mps.gz
python3 main.py cbc-test-set-master/ran12x21.mps.gz
python3 main.py cbc-test-set-master/ran14x18-disj-8.mps.gz
python3 main.py cbc-test-set-master/rd-rplusc-21.mps.gz
python3 main.py cbc-test-set-master/README.md
python3 main.py cbc-test-set-master/reblock115.mps.gz
python3 main.py cbc-test-set-master/reblock166.mps.gz
python3 main.py cbc-test-set-master/reblock354.mps.gz
python3 main.py cbc-test-set-master/reblock420.mps.gz
python3 main.py cbc-test-set-master/relax_and_mem.py
python3 main.py cbc-test-set-master/relax-grb-results.csv
python3 main.py cbc-test-set-master/rem_inf_unst.py
python3 main.py cbc-test-set-master/remove_most_similar.py
python3 main.py cbc-test-set-master/rentacar.mps.gz
python3 main.py cbc-test-set-master/resolve.sh
python3 main.py cbc-test-set-master/rgn.mps.gz
python3 main.py cbc-test-set-master/rlp1.mps.gz
python3 main.py cbc-test-set-master/rmatr100-p5.mps.gz
python3 main.py cbc-test-set-master/rmine10.mps.gz
python3 main.py cbc-test-set-master/rmine13.mps.gz
python3 main.py cbc-test-set-master/rmine15.mps.gz
python3 main.py cbc-test-set-master/rmine6.mps.gz
python3 main.py cbc-test-set-master/robot_sch_plain_10_211_3926_0.1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_plain_10_211_4288_0.05.mps.gz
python3 main.py cbc-test-set-master/robot_sch_plain_10_211_4682_0.01.mps.gz
python3 main.py cbc-test-set-master/robot_sch_plain_4_47_1673_0.01.mps.gz
python3 main.py cbc-test-set-master/robot_sch_plain_4_50_999_0.05.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_10_250_7703_0.01#0.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_10_250_7815_0.01#2.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_10_250_7815_0.05#2.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_10_250_7815_0.2#2.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_10_250_8063_0.05#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_10_250_8063_0.2#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_20_500_29840_0.01#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_20_500_29840_0.1#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_20_500_29840_0.2#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_20_500_30286_0.05#2.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_20_500_30334_0.2#0.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_4_100_1328_0.01#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_4_100_1328_0.05#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_4_100_1328_0.1#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_4_100_1328_0.2#1.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_4_100_1605_0.01#0.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_4_100_1605_0.2#0.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_4_100_1615_0.1#2.mps.gz
python3 main.py cbc-test-set-master/robot_sch_syn_plain_4_100_1615_0.2#2.mps.gz
python3 main.py cbc-test-set-master/rocI-4-11.mps.gz
python3 main.py cbc-test-set-master/rocII-9-11.mps.gz
python3 main.py cbc-test-set-master/rococoB10-011000.mps.gz
python3 main.py cbc-test-set-master/rococoC11-010100.mps.gz
python3 main.py cbc-test-set-master/rococoC11-011100.mps.gz
python3 main.py cbc-test-set-master/rococoC12-111000.mps.gz
python3 main.py cbc-test-set-master/roi2alpha3n4.mps.gz
python3 main.py cbc-test-set-master/roi5alpha10n8.mps.gz
python3 main.py cbc-test-set-master/roll3000.mps.gz
python3 main.py cbc-test-set-master/routing_0016.mps.gz
python3 main.py cbc-test-set-master/routing_GCM_0002.mps.gz
python3 main.py cbc-test-set-master/routing_GCM_0014.mps.gz
python3 main.py cbc-test-set-master/rout.mps.gz
python3 main.py cbc-test-set-master/rui-mbm.mps.gz
python3 main.py cbc-test-set-master/rvb-sub.mps.gz
python3 main.py cbc-test-set-master/s100.mps.gz
python3 main.py cbc-test-set-master/s1234.mps.gz
python3 main.py cbc-test-set-master/s250r10.mps.gz
python3 main.py cbc-test-set-master/s55.mps.gz
python3 main.py cbc-test-set-master/satellites1-25.mps.gz
python3 main.py cbc-test-set-master/satellites2-40.mps.gz
python3 main.py cbc-test-set-master/satellites3-25.mps.gz
python3 main.py cbc-test-set-master/satellites3-40-fs.mps.gz
python3 main.py cbc-test-set-master/savsched1.mps.gz
python3 main.py cbc-test-set-master/scpk1_core.mps.gz
python3 main.py cbc-test-set-master/scpk4.mps.gz
python3 main.py cbc-test-set-master/scpl4.mps.gz
python3 main.py cbc-test-set-master/scpm1.mps.gz
python3 main.py cbc-test-set-master/scpn2.mps.gz
python3 main.py cbc-test-set-master/sct1.mps.gz
python3 main.py cbc-test-set-master/sct2.mps.gz
python3 main.py cbc-test-set-master/sct31.mps.gz
python3 main.py cbc-test-set-master/sct32.mps.gz
python3 main.py cbc-test-set-master/sct5.mps.gz
python3 main.py cbc-test-set-master/seqsolve3short4288excess384.mps.gz
python3 main.py cbc-test-set-master/set1ch.mps.gz
python3 main.py cbc-test-set-master/set3-09.mps.gz
python3 main.py cbc-test-set-master/set5.mps.gz
python3 main.py cbc-test-set-master/seymour1.mps.gz
python3 main.py cbc-test-set-master/seymour-disj-10.mps.gz
python3 main.py cbc-test-set-master/seymour.mps.gz
python3 main.py cbc-test-set-master/shiftreg_2_7.mps.gz
python3 main.py cbc-test-set-master/shipsched.mps.gz
python3 main.py cbc-test-set-master/shs1014.mps.gz
python3 main.py cbc-test-set-master/shs1042.mps.gz
python3 main.py cbc-test-set-master/siena1.mps.gz
python3 main.py cbc-test-set-master/sing11.mps.gz
python3 main.py cbc-test-set-master/sing17.mps.gz
python3 main.py cbc-test-set-master/sing359.mps.gz
python3 main.py cbc-test-set-master/sing44.mps.gz
python3 main.py cbc-test-set-master/snip10x10-35r1budget17.mps.gz
python3 main.py cbc-test-set-master/snp-02-004-104.mps.gz
python3 main.py cbc-test-set-master/sorrell3.mps.gz
python3 main.py cbc-test-set-master/sorrell4.mps.gz
python3 main.py cbc-test-set-master/sorrell7.mps.gz
python3 main.py cbc-test-set-master/sorrell8.mps.gz
python3 main.py cbc-test-set-master/sp150x300d.mps.gz
python3 main.py cbc-test-set-master/sp97ar.mps.gz
python3 main.py cbc-test-set-master/sp97ic.mps.gz
python3 main.py cbc-test-set-master/sp98ar.mps.gz
python3 main.py cbc-test-set-master/sp98ic.mps.gz
python3 main.py cbc-test-set-master/sp98ir.mps.gz
python3 main.py cbc-test-set-master/splice1k1.mps.gz
python3 main.py cbc-test-set-master/sprint_hidden06_j.mps.gz
python3 main.py cbc-test-set-master/sprint_hint01_j.mps.gz
python3 main.py cbc-test-set-master/square23.mps.gz
python3 main.py cbc-test-set-master/square31.mps.gz
python3 main.py cbc-test-set-master/square37.mps.gz
python3 main.py cbc-test-set-master/square41.mps.gz
python3 main.py cbc-test-set-master/square47.mps.gz
python3 main.py cbc-test-set-master/stdc0025.mps.gz
python3 main.py cbc-test-set-master/stdc3282.mps.gz
python3 main.py cbc-test-set-master/stdc6262p.mps.gz
python3 main.py cbc-test-set-master/stdcd5113.mps.gz
python3 main.py cbc-test-set-master/stdnc2018.mps.gz
python3 main.py cbc-test-set-master/stein45.mps.gz
python3 main.py cbc-test-set-master/stockholm.mps.gz
python3 main.py cbc-test-set-master/stp3d.mps.gz
python3 main.py cbc-test-set-master/sts405.mps.gz
python3 main.py cbc-test-set-master/sts729.mps.gz
python3 main.py cbc-test-set-master/supportcase10.mps.gz
python3 main.py cbc-test-set-master/supportcase12.mps.gz
python3 main.py cbc-test-set-master/supportcase14.mps.gz
python3 main.py cbc-test-set-master/supportcase16.mps.gz
python3 main.py cbc-test-set-master/supportcase17.mps.gz
python3 main.py cbc-test-set-master/supportcase18.mps.gz
python3 main.py cbc-test-set-master/supportcase19.mps.gz
python3 main.py cbc-test-set-master/supportcase20.mps.gz
python3 main.py cbc-test-set-master/supportcase22.mps.gz
python3 main.py cbc-test-set-master/supportcase23.mps.gz
python3 main.py cbc-test-set-master/supportcase26.mps.gz
python3 main.py cbc-test-set-master/supportcase2.mps.gz
python3 main.py cbc-test-set-master/supportcase30.mps.gz
python3 main.py cbc-test-set-master/supportcase33.mps.gz
python3 main.py cbc-test-set-master/supportcase34.mps.gz
python3 main.py cbc-test-set-master/supportcase37.mps.gz
python3 main.py cbc-test-set-master/supportcase39.mps.gz
python3 main.py cbc-test-set-master/supportcase40.mps.gz
python3 main.py cbc-test-set-master/supportcase41.mps.gz
python3 main.py cbc-test-set-master/supportcase42.mps.gz
python3 main.py cbc-test-set-master/supportcase43.mps.gz
python3 main.py cbc-test-set-master/supportcase4.mps.gz
python3 main.py cbc-test-set-master/supportcase6.mps.gz
python3 main.py cbc-test-set-master/supportcase7.mps.gz
python3 main.py cbc-test-set-master/swath2.mps.gz
python3 main.py cbc-test-set-master/swath.mps.gz
python3 main.py cbc-test-set-master/System02_Example001.mps.gz
python3 main.py cbc-test-set-master/T1_300_5000_0.mps.gz
python3 main.py cbc-test-set-master/t1717.mps.gz
python3 main.py cbc-test-set-master/t1722.mps.gz
python3 main.py cbc-test-set-master/T2_200_2000_0.mps.gz
python3 main.py cbc-test-set-master/T2_300_1000_0.mps.gz
python3 main.py cbc-test-set-master/ta-BPWC_5_4_10.mps.gz
python3 main.py cbc-test-set-master/ta-BPWC_5_7_3.mps.gz
python3 main.py cbc-test-set-master/tanglegram4.mps.gz
python3 main.py cbc-test-set-master/tanglegram6.mps.gz
python3 main.py cbc-test-set-master/tbfp-bigm.mps.gz
python3 main.py cbc-test-set-master/tbfp-network.mps.gz
python3 main.py cbc-test-set-master/timtab1CUTS.mps.gz
python3 main.py cbc-test-set-master/timtab2.mps.gz
python3 main.py cbc-test-set-master/tokyometro.mps.gz
python3 main.py cbc-test-set-master/toll-like.mps.gz
python3 main.py cbc-test-set-master/tpl-tub-ss16.mps.gz
python3 main.py cbc-test-set-master/tpl-tub-ws1617.mps.gz
python3 main.py cbc-test-set-master/traininstance2.mps.gz
python3 main.py cbc-test-set-master/transportmoment.mps.gz
python3 main.py cbc-test-set-master/trd445c.mps.gz
python3 main.py cbc-test-set-master/trdca23002.mps.gz
python3 main.py cbc-test-set-master/trdcrooms.mps.gz
python3 main.py cbc-test-set-master/trdHard5600-6.mps.gz
python3 main.py cbc-test-set-master/trdHardCA4500-8.mps.gz
python3 main.py cbc-test-set-master/trdnc18.mps.gz
python3 main.py cbc-test-set-master/trdnc.mps.gz
python3 main.py cbc-test-set-master/trdta0010.mps.gz
python3 main.py cbc-test-set-master/trdta5581.mps.gz
python3 main.py cbc-test-set-master/trdta8265.mps.gz
python3 main.py cbc-test-set-master/trdta99.mps.gz
python3 main.py cbc-test-set-master/trdtatl9220.mps.gz
python3 main.py cbc-test-set-master/trdtaunimep.mps.gz
python3 main.py cbc-test-set-master/trento1.mps.gz
python3 main.py cbc-test-set-master/triptim1.mps.gz
python3 main.py cbc-test-set-master/triptim3.mps.gz
python3 main.py cbc-test-set-master/tw-myciel4.mps.gz
python3 main.py cbc-test-set-master/uccase10.mps.gz
python3 main.py cbc-test-set-master/uc-case11.mps.gz
python3 main.py cbc-test-set-master/uccase12.mps.gz
python3 main.py cbc-test-set-master/uc-case3.mps.gz
python3 main.py cbc-test-set-master/uccase7.mps.gz
python3 main.py cbc-test-set-master/uccase8.mps.gz
python3 main.py cbc-test-set-master/uct-subprob.mps.gz
python3 main.py cbc-test-set-master/umts.mps.gz
python3 main.py cbc-test-set-master/unitcal_7.mps.gz
python3 main.py cbc-test-set-master/unitcc.mps.gz
python3 main.py cbc-test-set-master/usafa.mps.gz
python3 main.py cbc-test-set-master/v150d30-2hopcds.mps.gz
python3 main.py cbc-test-set-master/v150_d50_2hopCDS.mps.gz
python3 main.py cbc-test-set-master/van.mps.gz
python3 main.py cbc-test-set-master/var-smallemery-m6j6.mps.gz
python3 main.py cbc-test-set-master/vpm1.mps.gz
python3 main.py cbc-test-set-master/vpphard2.mps.gz
python3 main.py cbc-test-set-master/vpphard.mps.gz
python3 main.py cbc-test-set-master/wachplan.mps.gz
python3 main.py cbc-test-set-master/wnq-n100-mw99-14.mps.gz
python3 main.py cbc-test-set-master/woodlands09.mps.gz
python3 main.py cbc-test-set-master/wqueens-100.mps.gz
python3 main.py cbc-test-set-master/wqueens-200.mps.gz
python3 main.py cbc-test-set-master/wqueens-300.mps.gz
python3 main.py cbc-test-set-master/wqueens-50.mps.gz
python3 main.py cbc-test-set-master/xhstt-italyp.mps.gz
python3 main.py cbc-test-set-master/xhstt-spainp.mps.gz
python3 main.py cbc-test-set-master/xmas10-2.mps.gz
python3 main.py cbc-test-set-master/xmas10.mps.gz
python3 main.py cbc-test-set-master/yue20013.1.150.mps.gz
python3 main.py cbc-test-set-master/yue20023.1.150.mps.gz
python3 main.py cbc-test-set-master/z26.mps.gz
python3 main.py cbc-test-set-master/zeil.mps.gz
python3 main.py cbc-test-set-master/zib54-UUE.mps.gz